/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "API_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BUSINESS_TABLE": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "BusinessTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CLIMATIQ_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_AUTH_ANDROID_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_AUTH_IOS_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_AUTH_WEB_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_MAPS_API_KEY_ANDROID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MAPTILERS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PROFILES_TABLE": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "ProfilesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SUPABASE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPABASE_PROJECT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
