Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Users"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "email-index"
          KeySchema:
            - AttributeName: "email"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: PAY_PER_REQUEST

  ProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Profiles"
      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "user_id"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

  VenuesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Venues"
      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "user_id"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

  ChatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Chats"
      AttributeDefinitions:
        - AttributeName: "venue_id"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "venue_id"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Messages"
      AttributeDefinitions:
        - AttributeName: "chat_id"
          AttributeType: "S"
        - AttributeName: "sent_at"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "chat_id"
          KeyType: "HASH"
        - AttributeName: "sent_at"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
