/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BUSINESS_TABLE": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "BusinessTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FACEBOOK_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PROFILES_TABLE": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "ProfilesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
